In [1]:
import numpy as np
#Making of numpy-array using the normal array
a=[1,2,3]
#Conversion of normal array into numpy-arrray
b=np.array(a) #this will make numpyArray from normal array given as argument

print(a)
print(type(a))
print(b)
print(type(b))
print(b.shape)

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
(3,)


### Numpy can only have homogeous types of data if any hetrogenous data comes, automatically all are converted into strings:
* **for getting in hetrogenous into homogenous "dtype" function is used, but it supports only possible conversions**

In [2]:
a=[1,2,3,32.3423,'Anshuman',34.3]
b=np.array(a)
print(b)
print(type(b))
print(type(b[2]))

['1' '2' '3' '32.3423' 'Anshuman' '34.3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [3]:
a=np.array([0,1,2,3])
print(a.shape)#This will return (4,) as it returns tupple bcz shape could be 2d or 3d, here is 1d so empty value after 1d


(4,)


In [4]:
#Conversion of hetrogenous(string) into homogenous:int
a=[1,2,3,32.3423,34.3] #"Anshuman" string had to be removed as string cannot be converted into int
b=np.array(a,dtype=int)
print(b)
print(type(b))


[ 1  2  3 32 34]
<class 'numpy.ndarray'>


In [5]:
#Making of reapating numpy-array
a=[1,2,3,32.3423,34.3] #"Anshuman" string had to be removed as string cannot be converted into int
b=np.array(a*3)
print(b)
print(type(b[2]))
print(type(b))


[ 1.      2.      3.     32.3423 34.3     1.      2.      3.     32.3423
 34.3     1.      2.      3.     32.3423 34.3   ]
<class 'numpy.float64'>
<class 'numpy.ndarray'>


In [6]:
#Using np.ones bydefault-type:float
#Making numpyArray of containing only 1-type:Float-bydefault
b=np.ones(3)#Makes numpy_array contining number of ones as per the argument and bydefault-valu=float
print(type(b[0]))
print(b)

#Converting them into int:
b=np.ones(3,dtype=int)
print(type(b[1]))
print(b)

<class 'numpy.float64'>
[1. 1. 1.]
<class 'numpy.int32'>
[1 1 1]


In [7]:
#Using np.zeros bydefault-type:float
#Making of numpyArray of containing only 0-type:float-bydefault
b=np.zeros(3)#makes numpy_array containing 0s number determined by the argument
print(type(b[1]))
print(b)

#Converting them into int
b=np.zeros(3,dtype=int)
print(type(b[1]))
print(b)

<class 'numpy.float64'>
[0. 0. 0.]
<class 'numpy.int32'>
[0 0 0]


In [8]:
#Using np.full() bydefault-type:int
#Its takes argument first for dimension or number of repetation and then for the value
b=np.full(3,5,dtype=float) #Create an array of size of repeation as first arg and value as second 
print(b)

[5. 5. 5.]


In [9]:
#Using np.empty():used to generate array of random numbers
#It takes size-argument and dtype only not value required as generates random one
b=np.empty(2)
print(b)

[2.12199579e-314 6.36598737e-314]


In [10]:
#np.randaom.rand():Takes size as input and generated random values ranged between(0to1)
b=np.random.rand(3) #range 0 to 1
print(b)
# by multiplying number with funciton inreases the range
c=np.random.rand(3)*10 #range 0 to 10
print(c)

[0.91356275 0.17990525 0.99591873]
[6.45133994 2.76962876 4.96777529]


In [11]:
#np.random.randint(low,high,size,dtype):generated random nd-array
#low is compulsory and inclusive,deafult=0
#high is optional and exclusive
#size can nd
a=np.random.randint(1,5,3)
print(a)

[1 4 2]


In [12]:
# Creating NumpyArray using "np.arange(start,stop,step,dtype)""
#Start is bydefault=0,stop is exclusive,step-bydefault=(+1),default:int
#Mandtory:"stop" only
a=np.arange(0,10,1)
print(a)
print(type(a[1]))
print()
b=np.arange(10)
print(b)
print(type(b[1]))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.int32'>

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.int32'>


In [13]:
#Creating NumpyArray using "np.linspace(start,stop,num,endpoint,retstep,dtype,axis)"
#start and stop are both inclusive unlike arange where stop is excluded
#start is mandtory,stop-mandtory
#num:number of samples to generate is given:defaultVal=50 ,it will decide what is stepValue according to the sample
#default type=float,endpoint=True->bydefault which will include the stop else not
#retStep=True:returns=step,axis=0,means operation done in rowise(default) else coloumnwise ,1 requires 2d dimension whereas 0 is default 1D
a=np.linspace(0,100)
print(a[2]-a[1])#Will give the stepValue chosen by the function
print(a[4]-a[3])#DoubleCheck of stepvalue
print(a)

2.0408163265306123
2.040816326530612
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [14]:
a=np.linspace(1,10,5,retstep=True)
print(a)#Will give array with stepValue written at the end

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


### Diference between np.arange and np.linspace is that :
* **In in np.arange, we have control over step value**
* **In np.linspace, we have control over the samples to generated**

## Creation 2D Numpyarray

In [15]:
#Just add argument defining (row,coloumn) in place arg defining dimension or number of repetaion
c=np.ones((2,3),dtype=int)
print(type(c[1][1]))
print(c)

<class 'numpy.int32'>
[[1 1 1]
 [1 1 1]]


In [16]:
#2D array for zeros
c=np.zeros((3,3),dtype=int)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
#2d array for any inputed-same-random value
c=np.full((2,3),5,dtype=int)
print(c)

[[5 5 5]
 [5 5 5]]


In [18]:
#2d array of any andom value genrated by the compilier basically garbage value 
c=np.empty((3,2),dtype=int)
print(c)

[[ 240556494 1075433004]
 [ 535376820 1074145331]
 [2080977034 1075044096]]


In [19]:
#Problem:6 converting normal 2d list into numpy 2d Array
List=[[1,2,3],[4,5,6],[7,8,9]]
NumpyArray=np.array(List)
print(List)
print(NumpyArray)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#Problem: 7, making numpy-array of size-10 in which all are 0 but 5th one is 1
#np.append, used to merge only 2 numpy arrays into one-new variable
a=np.zeros(4,dtype=int)
print(a)
b=np.ones(1,dtype=int)
print(b)
c=np.zeros(5,dtype=int)
print(c)

#Using np.append-only merging 2 at a time into new var
d=np.append(a,b)
print(d)
e=np.append(d,c)
print(e)

[0 0 0 0]
[1]
[0 0 0 0 0]
[0 0 0 0 1]
[0 0 0 0 1 0 0 0 0 0]


In [21]:
#2d matrix of generating random values between 0 to 1 
b=np.random.rand(2,4)
print(b)
# by multiplying number with range can increase the range
c=np.random.rand(2,4)*100
print(c)

[[0.94396844 0.71309089 0.78507726 0.83807642]
 [0.9375001  0.89917416 0.25285579 0.32606143]]
[[41.69460096 74.77840437 55.97621214 58.66004039]
 [ 9.36241742 31.30922048 15.7924445  41.56791944]]


In [22]:
#np.random.randint(low,high,size,dtype):generated random nd-array
#low is compulsory and inclusive,deafult=0
#high is optional and exclusive
#size can nd
a=np.random.randint(1,5,size=(2,3))
print(a)

[[3 1 2]
 [3 1 4]]


## Matrix

In [23]:
#np.identity used for making Identiy-Matrix of given arg as dimension
#Takes only one intput-arg as input-dimension
a=np.identity(3,dtype="int")
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [24]:
#np.eye takes 2-inputs as argument for matrix-dimension and gives identity matrix
a=np.eye(2,3,dtype='int')
print(a)
print(a.shape)

[[1 0 0]
 [0 1 0]]
(2, 3)


## NumpyArray characterstics:

In [25]:
import numpy as np
#numpy array is a collection of pointers which points 4 different attribute
li=[1,2,3,4,5]
arr=np.array(li)
print(arr)
print(arr.data)#points to first element of the array
print(arr.shape)#represents size of the array
print(arr.dtype)#represents the the data-type 
print(arr.strides)#represents number of bytes to be skipped to get to the next element 

[1 2 3 4 5]
(5,)
int32
(4,)


In [26]:
li_2d=[[1,2,3],[4,5,6],[6,7,8],[12,23,34]]
arr_2d=np.array(li_2d)

print(li_2d)
print(arr_2d)
print(arr_2d.data)#points to first element of the array
print(arr_2d.shape)#represents size of the array
print(arr_2d.dtype)#represents the the data-type 
print(arr_2d.strides)#represents number of bytes to be skipped to get to the next element 
#In stride, we get (12,4), means for going to next row we have to skip 3 integers means 3x4=12 bytes
#but for going to next coloumn just skip one integer means 4bytes


[[1, 2, 3], [4, 5, 6], [6, 7, 8], [12, 23, 34]]
[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [12 23 34]]
(4, 3)
int32
(12, 4)


## Slicing and indexing:


In [27]:
#Slicing of Numpy-1D Array is same as normal array:
li=[1,2,3,4,5]
arr=np.array(li)
print(li[2])
print(arr[2])
print(li[1:4])
print(arr[1:4])

3
3
[2, 3, 4]
[2 3 4]


In [28]:
# Slicing of 2D NumpyArray:
li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d=np.array(li_2d)

print(arr_2d) #whille working with 2D, refer to this diagram in which rows are(0,1,2,3) and col are(0,1,2,3)

#[][]:row,coloumn
print(li_2d[1][1])
print(arr_2d[1 ,2])
# print(li_2d[2,1]) #Error
print(arr_2d[2,1])#Only in numpy2d Array could write this way also

#SLicing
#fix row and vary coloumn selection:[5,6,7]
print("FixRow for Li:",li_2d[1][:3]) 
print("FixRow for Arr:",arr_2d[1,:3]) 

#Fix coloumn and vary row selection(little-bit different):[4,8,12]
print("FixedColoumn for Li:",li_2d[:3][1] )#This is different bcz li_2d[:3] becomes another array and giving coloumn as input becomes selection index of that array
x=li_2d[:3]#Becomes a separate array
print(x)#printed and checked
print(x[1])#given coloumn interpreted as index of that new_array not expexted 

print("FixedColoumn for Arr:",arr_2d[:3,3])#got answer as expected

#Vary row and var col: [10,11],[14,15]
print(arr_2d[2:4,1:3]) #got ans as expected
print(li_2d[2:4][1:3]) #not expexted ans

#Therefore 2d array problem Numpy array are best

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
6
7
10
FixRow for Li: [5, 6, 7]
FixRow for Arr: [5 6 7]
FixedColoumn for Li: [5, 6, 7, 8]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[5, 6, 7, 8]
FixedColoumn for Arr: [ 4  8 12]
[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


In [29]:
#Problems:
li_2d=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr_2d=np.array(li_2d)
print(arr_2d)
print(arr_2d.shape)

print("1:",arr_2d[2,:3])
print("2:",arr_2d[1:4,3])
print("3:",arr_2d[2:5,])
print("4:",arr_2d[1:3,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
1: [11 12 13]
2: [ 9 14 19]
3: [[11 12 13 14 15]
 [16 17 18 19 20]]
4: [[ 7  8]
 [12 13]]


## Mathematical Operations

In [30]:
## li=[1,2,3,4,5,6]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)

print(li)
print(a)
print(b)
print()
#Adding 1 to every element of the list
#In case of list, iteration to each element should take place:
li=[i+1 for i in li]
print(li)
print()
#In case of numpy array:Simply add 1 to array, will automatically add with all
#That is the significance of numpyArray,its quite fast bcz it used vectorisation
a+=1
print(a)


[1, 2, 3, 4, 5]
[11 12 16 15  5]
[ 1 10 12 18  9]

[2, 3, 4, 5, 6]

[12 13 17 16  6]


In [31]:
#Addition of 2-Arrays:
#in normal array we have to iterate to every item but 
#in numpy Array by use of vectorisation , with the help of lesser loop all could be done at once
c=a+b
print(c)

[13 23 29 34 15]


In [32]:
#Substraction of 2-Arrays
print(a)
print(b)
d=a-b
d

[12 13 17 16  6]
[ 1 10 12 18  9]


array([11,  3,  5, -2, -3])

In [33]:
#Multiplication of 2Arrays
e=a*b
e

array([ 12, 130, 204, 288,  54])

In [34]:
#Division of 2Arrays
f=a//b
f

array([12,  1,  1,  0,  0])

In [35]:
#Exponantiation
g=a**b #a raised to the power b
g

array([        12,  419538377, 1333592769,          0,   10077696])

In [36]:
#Other operations:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin())#Gives the index of minimum-element
print(a.argmax())#Gives the index of maximum element

[12 13 17 16  6]
64
12.8
6
17
4
2


In [37]:
#Relational operation with every iem of the arrays
print(a)
print(b)
print(a>b)
print(a<b)
print(a==b)

[12 13 17 16  6]
[ 1 10 12 18  9]
[ True  True  True False False]
[False False False  True  True]
[False False False False False]


In [38]:
#Logical Operations on every item of the array
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


# Boolean Indexing
* Avery powerful technique which we can apply it on our data and required data can be extracted and updated


In [39]:
import numpy as np
a=np.random.randint(1,30,(5,6))#Created 5x6 matrix of random value from range 1to29
print(a)

#Extract thsoe values which are greater than 20,extract them and change them to 100
#Extracted matched number's in booleans
bool_arr=a>20
print(bool_arr)
print(type(bool_arr))#The operatio on numpyArray stored in another array is bydefault numpy array
#Now extracted those numbers with help of their boolean
ans=a[bool_arr]#passed the bool_arr into original, so that only true one comes into ans_array
print(ans)
a[bool_arr]=100#And replace those true values
a
#Note:In case of boolean arrays the size should be same

[[27 23 12 12 10  5]
 [14 18 19 10 15 25]
 [ 4 15 28  1 26 18]
 [24 23 25 22  3  7]
 [ 9 12  3 18 15 10]]
[[ True  True False False False False]
 [False False False False False  True]
 [False False  True False  True False]
 [ True  True  True  True False False]
 [False False False False False False]]
<class 'numpy.ndarray'>
[27 23 25 28 26 24 23 25 22]


array([[100, 100,  12,  12,  10,   5],
       [ 14,  18,  19,  10,  15, 100],
       [  4,  15, 100,   1, 100,  18],
       [100, 100, 100, 100,   3,   7],
       [  9,  12,   3,  18,  15,  10]])

In [41]:
c=np.random.randint(1,10,(2,2))
print(c)
c_bool=np.array([[True,False],[True,False],[True,True]])
print(c_bool)
# c[c_bool]
#If the size is not matched then this error comes

[[9 6]
 [6 2]]
[[ True False]
 [ True False]
 [ True  True]]


In [42]:
#Only at 4th coloumn extract the number same as 100 update them to 10000000
b=a
print(b)
#Extraction of the matched number in boolean
b_bool=b[:,4]==100
print(b_bool)

b[b_bool,3]=10000000#passed boolean in place of row, as it have selected rows as True for updation
print(b)

[[100 100  12  12  10   5]
 [ 14  18  19  10  15 100]
 [  4  15 100   1 100  18]
 [100 100 100 100   3   7]
 [  9  12   3  18  15  10]]
[False False  True False False]
[[     100      100       12       12       10        5]
 [      14       18       19       10       15      100]
 [       4       15      100 10000000      100       18]
 [     100      100      100      100        3        7]
 [       9       12        3       18       15       10]]


In [ ]:
#Only at 2nd row extract the number same as 100 update them to 923084
b=a
print(b)
b_bool=b[1,:]==100
print(b_bool)#Extraction of matched number in boolean

b[1,b_bool]=923084#passed boolean in place of col, as it have selected col as True for updation
print(b)

## BroadCasting
* Specifies how numpy will treat the unequal size array
* **Compatibility comes either the *dimesnion should be equal* or *One of them should have 1 as their dimension and other one should same*.**

In [ ]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))
print(x)
print(y)
ans=x-y#operations are valid the dimensions are same
ans

In [ ]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3))#nothing means bydefault one:(3,1)
print(x)
print(y)
ans=x-y#also no error as one of them have diemnsion atleast 1 and other same
ans #the one row is operating with ohter row also 

In [ ]:
#Using transpose if dimensions are : (x,y) and (y,x)
x=np.random.randint(1,10,(2,3))
y=np.random.randint(1,10,(3,2))
print(x)
print(y)
# x-y gives error as dimnesion are different
#Either use transpose on y or x , to make their dimenion same:
y=np.transpose(y)
print(y)#Now dimension changd to (2,3) same as x
x-y

In [ ]:
#Using resize():It resizes the dimnsion to the given argument dimension
#The new array comes with re-arangemnet of new data or with 0 for extending dimension it adds extra 0s
x=np.random.randint(1,10,(3,3))
print(x)
print(x.resize(2,6))#added extra 0
x
x.resize(2,4)      
print(x)#changed the sequence and deleted 1 as not required

In [ ]:
#Using reshape():
# It resize the dimension but never changes the arrangemnet of the orogninal sequence and never adds extra 0 and never delets them
x=np.random.randint(1,10,(2,3))
print(x)
x.reshape(3,2)

In [ ]:
#Problem:
#np.sort(array,axis)
li=[[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]]
a=np.array(li)
print(a)
np.sort(a,axis=0)
# kind:[Quick,merge,heap,stable] sorts.default=Quick
#axis-None:flattens the array,defaualt=-1or1:Both same,Sort along the last axis 
# axis:0:sort along the first axis and bottom goes up and up goes to bottom

In [ ]:
#Problem: Make a coulom with entry Killed+wounded
import numpy as np
import csv

file_obj=open('year2017.csv','r')#This method was introduced in FileSystem
data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
Wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    Wounded.append(row["Wounded"])
#Each and every value is string
print(type(killed[2]))
print(type(Wounded[2]))

# print(killed)
#Conversion of dataItem into int help of numpy:
#First we have to deal with missing values
#Firstly create numpyArray else np cant be used
np_killed=np.array(killed)
print(np_killed)
np_wounded=np.array(Wounded)
print(np_wounded)

#We have to replace the missing values with zero, as if we delete them then arrays got smaller and killed+Wound for the reapective row would be different
#This could be done by boolean indexing
bool_killed=np_killed==''
print(bool_killed)#Got the boolean wrt missingValues
np_killed[bool_killed]=0#replaced them with zero,True means reaplced by 0 

bool_wounded=np_wounded==''
print(bool_wounded)
np_wounded[bool_wounded]=0
 
#Now there is on missing value present, successfully conversion
killed=np.array(np_killed,dtype=int)
wounded=np.array(np_wounded,dtype=int)

#Killed+Wounded:
killed_wounded=killed+wounded

#Now we have to know the killed+wounded only of India:
#NumpyArray
np_country=np.array(country)
bool_India=np_country=="India"
print(bool_India)#Now we places which have India means true else false

#The we could transfer this booleans to killed+wound to get only True -values means Indian-Values 
ans=killed_wounded[bool_India]#This has killed+wounded of India

#Now to get the summation
print(np.sum(ans))#Total killed+wounded in India
print(np.sum(killed_wounded)) #Total killed+wounded in total